<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <WarnOn>3390;$(WarnOn)</WarnOn>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Helpers.fs" />
    <Compile Include="ActorTests.fs" />
    <Compile Include="SupervisionTests.fs" />
    <Compile Include="BuilderTests.fs" />
    <Compile Include="LifecycleTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.2.0" />
    <PackageReference Include="Scriptorium.Quill" Version="0.5.1" />
    <PackageReference Include="Scriptorium.Nib" Version="0.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../src/Fable.Actor/Fable.Actor.fsproj" />
  </ItemGroup>
</Project>
